name: Update maven-snapshot Chocolatey package
#on:
#  schedule:
#    - cron:  '0 * * * *'
on: [push]
jobs:
  update-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "martinkanters@noreply.github.com"
          git config --global user.name "Martin Kanters"

      - name: Update package if needed
        shell: bash
        run: |
          cd maven-snapshot/
          base_jenkins_url="https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven/job/master/"
          last_successful_build=$(curl -q "${base_jenkins_url}/api/json" | jq '.lastSuccessfulBuild')
          
          last_persisted_build_number=$(cat last-build.txt)
          last_successful_build_number=$(echo $last_successful_build | jq '.number')
          
          if [ "$last_persisted_build_number" == "$last_successful_build_number" ]; then
            echo "No new successful Maven master build detected, nothing to do"
          else
            echo "Found new successful Jenkins build: ${last_successful_build_number}, old: ${last_persisted_build_number}"
            successful_build_url=$(echo $last_successful_build | jq -r '.url')
            zip_artifact_path=$(curl -q "${successful_build_url}api/json" | jq -r '.artifacts[]|select(.fileName | test("^apache-maven-\\d.*-bin\\.zip$"))|.relativePath')
            zip_artifact_url="${successful_build_url}artifact/${zip_artifact_path}"
            zip_hash=$(curl -q "$zip_artifact_url" | sha256sum | awk '{print $1}')
            new_package_version=$(date +'%Y%m%d.%H%M')
            escaped_zip_artifact_url=$(printf '%s\n' "$zip_artifact_url" | sed -e 's/[\/&]/\\&/g')
            
            sed -ir 's/$checksum =.*/$checksum = \"'${zip_hash}'\"/' tools/chocolateyinstall.ps1
            sed -ir 's/$url =.*/$url = \"'${escaped_zip_artifact_url}'\"/' tools/chocolateyinstall.ps1
            sed -ir 's/    <version>.*/    <version>'${new_package_version}'<\/version>/' maven-snapshot.nuspec
            echo $last_successful_build_number > last-build.txt
            
            git status
            git diff
          fi
          
          
      - name: Persist changes
        shell: bash
        run: |
          #git status
          #git diff
          #git commit -am "Update to latest Maven snapshot" || exit 0
          #git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          #git push github HEAD:${GITHUB_REF}